#!/bin/bash

# Manifested Laziness
alias vi='/usr/bin/vim'
alias aliases='vim ~/.aliases'
alias vimrc='vim ~/.vimrc'

# Directory movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Listings
alias ls='ls -G'
alias l='ls -l'
alias ll='ls -l'
alias la='ls -lah'
alias lh='ls -lh'
alias tree="ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias cl='clear'

# Make things colourful
alias grep='grep -n --color=auto'

# list directory contents on change
function cd {
    builtin cd "$@" && l
}