#!/bin/bash

# some ls aliases
alias l='ls -l'
alias la='ls -A'
alias lg='ls -G'
alias lh='ls -lah'
alias tree="ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"

alias vim='/usr/bin/vim'
alias cl='clear'

# Manifested Laziness
alias aliases='vim ~/.aliases'
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias flush='dscacheutil -flushcache'

# Directory movement
alias ..='cd ..'
alias ...='cd ../..'

# dev folder
alias dev='cd $DEV_ROOT'
alias cdv='cd $DEV_ROOT/prototype/vagrant-server'
alias vmup='cd $DEV_ROOT/prototype/vagrant-server && vagrant up'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# list directory contents on change
function cd {
    builtin cd "$@" && l
}

# remove duplicates while preserving input order
function dedup {
   awk '! x[$0]++' $@
}

# removes $HISTIGNORE commands from input
function remove_histignore {
   if [ -n "$HISTIGNORE" ]; then
      # replace : with |, then * with .*
      local IGNORE_PAT=`echo "$HISTIGNORE" | sed s/\:/\|/g | sed s/\*/\.\*/g`
      # negated grep removes matches
      grep -vx "$IGNORE_PAT" $@
   else
      cat $@
   fi
}

# clean up the history file by remove duplicates and commands matching
# $HISTIGNORE entries
function history_cleanup {
   local HISTFILE_SRC=$HISTFILE
   local HISTFILE_DST=/tmp/.$USER.bash_history.clean
   if [ -f $HISTFILE_SRC ]; then
      \cp $HISTFILE_SRC $HISTFILE_SRC.backup
      dedup $HISTFILE_SRC | remove_histignore >| $HISTFILE_DST
      \mv $HISTFILE_DST $HISTFILE_SRC
      chmod go-r $HISTFILE_SRC
      history -c
      history -r
   fi
}
