# file: dotfiles.yml
- name: Set up local workstation
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  gather_subset: env

  tasks:
    # copy aliases to home folder
    - name: Copy aliases to home folder
      copy:
        src: "resources/aliases"
        dest: "{{ ansible_env['HOME'] }}/.aliases"
        mode: '644' # 0644
        force: yes

  roles:
    - git
    - vim
    - zsh