#!/bin/bash

# Manifested Laziness
alias vi='/usr/bin/vim'
alias aliases='vim ~/.aliases'
alias vimrc='vim ~/.vimrc'

# Directory movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Listings
alias ls='ls -G'
alias l='ls -l'
alias ll='ls -l'
alias la='ls -lah'
alias lh='ls -lh'
alias tree="ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias cl='clear'

# Make things colourful
alias grep='grep -n --color=auto'

# list directory contents on change
function cd {
    builtin cd "$@" && l
}

#### aliases for development ####
# pbcopy
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# kubernetes
alias k='kubectl'
function klocal {
    export KUBECONFIG=~/.kube/config
}
function kpi5 {
    export KUBECONFIG=~/.kube/config-pi5
}
function kai {
    export KUBECONFIG=~/.kube/config-ai
}

# Autocomplete
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion