---
# file: roles/zsh/tasks/main.yml
- name: Installs zsh packages | apt
  become: true
  become_user: root
  apt:
    name:
      - zsh
      - curl
      - tmux
      - fonts-powerline
      - xclip

- name: Sets zsh as default shell for logged user | command
  become: true
  become_user: root
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Checks for oh-my-zsh installation | stat
  stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Installs oh-my-zsh | raw
  raw: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: zsh | Copy .zshrc | template
  template:
    src: "zshrc.j2"
    dest: "{{ user_home }}/.zshrc"
    mode: '644' # 0644
    force: yes
