---
###############################################################################
# Git installation

- name: Git | Installs git | apt
  become: true
  become_user: root
  apt:
    name: git
    state: present

- name: copy gloable git ignore
  copy:
    src: "files/gitignore_global"
    dest: "{{ lookup('env', 'HOME') }}/.gitignore_global"
    mode: '644' # 0644
    force: yes

- name: Git | Copies git config | template
  template:
    src: "gitconfig.j2"
    dest: "{{ user_home }}/.gitconfig"
    mode: '644' # 0644
    force: yes


