---
# file: roles/vim/tasks/main.yml
- name: Installs vim package
  become: yes
  become_user: root
  apt:
    name: vim
    state: present

- name: Copy vim files
  copy:
    src: "files/vimrc"
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
    mode: '644' # 0644
    force: yes

- name: Copy vim folders
  copy:
    src: "files/vim/"
    dest: "{{ lookup('env', 'HOME') }}/.vim/"
    mode: '755'
    force: yes
